defaults: &defaults
  working_directory: /home/circleci/build
  environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    K8S_NAMESPACE: "Change-To-Your-Products-Namespace"
    KUBECONFIG: "eks-development-kubeconfig"
    SERVICE_NAME: "hello-world-simple-website"
    SERVICE_IMAGE_NAME: "815667184744.dkr.ecr.us-east-2.amazonaws.com/hello-world-simple-website"
    PROJ_ROOT_DIR: "/home/circleci/build"
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
  docker:
    - image: 815667184744.dkr.ecr.us-east-2.amazonaws.com/atlas-build:latest
    - image: selenium/standalone-chrome:3.141.59-titanium

version: 2
jobs:
  build_proj:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "Store Build Version"
          command: |
            mkdir -p workspace
            echo "1.0.0-$CIRCLE_BUILD_NUM" > workspace/build-version
      - run:
          name: "Build"
          command: bash build.sh
      - store_test_results:
          path: Build/output/tests
      - store_artifacts:
          path: Build/output/tests/CodeCoverage/Reports
          destination: CodeCoverage                    
      - save_cache:
          key: v1-build-out-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - ~/.nuget/packages
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - build
            

workflows:
  version: 2

  build-deploy:
    jobs:
      - build_proj

      
